from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import (credito, controladoria, secretaria, cobranca, adm, cadastro, retaguarda, financeiro,
                    gestaoNegocios, gestaoControle, formularios, security, rh, pages, cooperar, ti, produtoServico,
                    gestaoRisco, padigital, padf, planaltina, formosa, vicente, saojoao, saosebas, marketing, sia, gestaoRecursos,
                    recepcao)

urlpatterns = [
    path('base', pages.base, name='base'),

    path('login', security.loginPage, name='login'),
    path('conta', pages.conta, name='conta'),
    path('profile/<int:user_id>', pages.profile, name='profile'),
    path('', pages.home, name='home'),
    path('departamentos', pages.departamentos, name='departamentos'),
    path('processos_user', pages.processos_user, name='processos_user'),

    path('kanban/', pages.kanban_view, name='kanban'),
    path('kanban_user/', pages.kanban_view_user, name='kanban_user'),
    path('chat', pages.chat, name='chat'),
    path('cards_kanban_api/', pages.card_kanban_api, name='cards_kanban_api'),
    path('card_detl/<int:card_id>', pages.card_detl, name='card_detl'),
    path('enviar_resposta/<int:card_id>', pages.enviar_resposta, name='enviar_resposta'),
    path('get_messages/<int:card_id>', pages.get_messages, name='get_messages'),
    path('registrar_atendimento/<int:card_id>', pages.registrar_atendimento, name='registrar_atendimento'),
    path('encaminhar_card/<int:card_id>', pages.encaminhar_card, name='encaminhar_card'),
    path('compartilhar_card/<int:card_id>', pages.compartilhar_card, name='compartilhar_card'),
    path('transferir_card/<int:card_id>', pages.transferir_card, name='transferir_card'),
    path('presonalizar_card/<int:card_id>', pages.presonalizar_card, name='presonalizar_card'),
    path('concluir_card/<int:card_id>', pages.concluir_card, name='concluir_card'),
    path('finalizar_card/<int:card_id>', pages.finalizar_card, name='finalizar_card'),
    path('get_user_rating/<int:card_id>', pages.get_user_rating, name='get_user_rating'),
    path('avaliar_card/<int:card_id>', pages.avaliar_card, name='avaliar_card'),
    path('reabrir_card/<int:card_id>', pages.reabrir_card, name='reabrir_card'),
    path('history_request', pages.history_request, name='history_request'),
    path('get_card_details', pages.get_card_details, name='get_card_details'),
    path('notificacao_lida/<int:notification_id>', pages.notificacao_lida, name='notificacao_lida'),
    path('get_message_history/<int:card_id>/', pages.get_message_history, name='get_message_history'),

    path('malotes', pages.malotes, name='malotes'),
    path('ccc', pages.ccc, name='ccc'),
    path('processa_cupons', pages.processa_cupons, name='processa_cupons'),

    path('gestaoControle', gestaoControle.home, name='gestaoControle'),
    path('contabilidade', gestaoControle.contabilidade, name='contabilidade'),
    path('relatorios', gestaoControle.relatorios, name='relatorios'),
    path('estrategico', gestaoControle.estrategico, name='estrategico'),
    path('inadimplencia', gestaoControle.inadimplencia, name='inadimplencia'),
    path('qqs', gestaoControle.qqs, name='qqs'),
    path('pesquisa', gestaoControle.pesquisa, name='pesquisa'),
    path('gestaoRelatorios', gestaoControle.gestaoRelatorios, name='gestaoRelatorios'),
    path('rankingsicoob', gestaoControle.rankingsicoob, name='rankingsicoob'),

    path('gestaoNegocios', gestaoNegocios.home, name='gestaoNegocios'),
    path('gestaoMetas', gestaoNegocios.gestaoMetas, name='gestaoMetas'),
    path('diaria', gestaoNegocios.diaria, name='diaria'),
    path('listasPropensos', gestaoNegocios.listasPropensos, name='listasPropensos'),
    path('pronampe', gestaoNegocios.pronampe, name='pronampe'),
    path('relatorioVisitas', gestaoNegocios.relatorioVisitas, name='relatorioVisitas'),
    path('planoMetas', gestaoNegocios.planoMetas, name='planoMetas'),
    path('lastro', gestaoNegocios.lastro, name='lastro'),
    path('credito', gestaoNegocios.credito, name='credito'),
    path('operacoes_credito', gestaoNegocios.operacoes_credito, name='operacoes_credito'),
    path('credito_liberacao', gestaoNegocios.credito_liberacao, name='credito_liberacao'),
    path('calendario', gestaoNegocios.calendario, name='calendario'),
    path('gestaoCarteira', gestaoNegocios.gestaoCarteira, name='gestaoCarteira'),
    path('carteiras', gestaoNegocios.carteiras, name='carteiras'),

    path('coopera', cooperar.coopera, name='coopera'),
    path('relacionamento', cooperar.relacionamento, name='relacionamento'),
    path('simulador', cooperar.simulador, name='simulador'),
    path('tabela', cooperar.tabela, name='tabela'),
    path('india', cooperar.india, name='india'),
    path('portifolio', cooperar.portifolio, name='portifolio'),
    path('capital', cooperar.capital, name='capital'),
    path('dados', cooperar.dadosConsolidados, name='dados'),

    path('logout', security.logout_view, name='logout'),
    path('new_login_page', pages.new_login_page, name='new_login_page'),
    path('redefinir_senha', security.redefinir_senha, name='redefinir_senha'),
    path('inativar_usuario/<int:user_id>', security.inativar_usuario, name='inativar_usuario'),

    path('formMidia', formularios.formMidia, name='formMidia'),
    path('formDep', formularios.formDep, name='formDep'),
    path('formEnd', formularios.formEnd, name='formEnd'),
    path('formEsc', formularios.formEsc, name='formEsc'),
    path('formCert', formularios.formCert, name='formCert'),
    path('formProf', formularios.formProf, name='formProf'),
    path('formBanc', formularios.formBanc, name='formBanc'),
    path('formOut', formularios.formOut, name='formOut'),

    path('rg', formularios.rg, name='rg'),
    path('cnh', formularios.cnh, name='cnh'),
    path('cpf', formularios.cpf, name='cpf'),
    path('reservista', formularios.reservista, name='reservista'),
    path('titulo', formularios.titulo, name='titulo'),
    path('clt', formularios.clt, name='clt'),
    path('residencia', formularios.residencia, name='residencia'),
    path('certidao', formularios.certidao, name='certidao'),
    path('admissional', formularios.admissional, name='admissional'),
    path('periodico', formularios.periodico, name='periodico'),

    path('security/password_reset', security.password_reset, name='password_reset'),
    path('security/password_done', security.password_done, name='password_done'),

    path('rh', rh.rh_home, name='rh_home'),
    path('rh/dashboard', rh.rh_dash, name='rh_dashboard'),
    path('rh/processo-seletivo', rh.pro_seletivo, name='pro-seletivo'),
    path('rh/ferias', rh.ferias, name='ferias'),
    path('rh/anbima', rh.anbima, name='anbima'),
    path('rh/colaboradores', rh.colaboradores, name='colaboradores'),
    path('rh/usuario', pages.usuario, name='usuario'),
    path('rh/new_request', rh.new_request, name='new_request'),
    path('rh/salvar_malote', rh.salvar_malote, name='salvar_malote'),
    path('rh/processos', rh.processos, name='processos'),
    path('rh/salvar_etica', rh.salvar_etica, name='salvar_etica'),
    path('rh/request_ci_rh', rh.request_ci_rh, name='request_ci_rh'),
    path('rh/request_apontamentos_rh', rh.request_apontamentos_rh, name='request_apontamentos_rh'),
    path('rh/request_ferias', rh.request_ferias, name='request_ferias'),

    path('ti', ti.ti_home, name='ti_home'),
    path('ti/new_request', ti.new_request, name='new_request'),
    path('ti/request_acessos', ti.request_acessos, name='request_acessos'),
    path('ti/request_equipamentos', ti.request_equipamentos, name='request_equipamentos'),
    path('ti/request_desenvolvimento', ti.request_desenvolvimento, name='request_desenvolvimento'),
    path('ti/request_servicos', ti.request_servicos, name='request_servicos'),
    path('ti/estoque', ti.estoque, name='estoque'),
    path('ti/estoque/notebook', ti.notebook, name='notebook'),
    path('ti/processos', ti.processos, name='processos'),
    path('ti/request_ci', ti.request_ci, name='request_ci'),
    path('ti/request_apontamentos', ti.request_apontamentos, name='request_apontamentos'),

    path('retaguarda_home', retaguarda.retaguarda_home, name='retaguarda_home'),
    path('new_request_retaguarda', retaguarda.new_request_retaguarda, name='new_request_retaguarda'),
    path('salvar_malote_retaguarda', retaguarda.salvar_malote_retaguarda,
           name='salvar_malote_retaguarda'),
    path('processos_retaguarda', retaguarda.processos_retaguarda,name='processos_retaguarda'),
    path('request_apontamentos_ret', retaguarda.request_apontamentos_ret,name='request_apontamentos_ret'),
    path('request_ci_ret', retaguarda.request_ci_ret, name='request_ci_ret'),

    path('produtoServico_home', produtoServico.produtoServico_home, name='produtoServico_home'),
    path('request_produto_servico', produtoServico.request_produto_servico,
           name='request_produto_servico'),
    path('salvar_malote_PS', produtoServico.salvar_malote_PS, name='salvar_malote_PS'),
    path('processos_PS', produtoServico.processos_PS, name='processos_PS'),
    path('request_ci_ps', produtoServico.request_ci_ps, name='request_ci_ps'),
    path('request_apontamentos_ps', produtoServico.request_apontamentos_ps, name='request_apontamentos_ps'),

    path('financeiro_home', financeiro.financeiro_home, name='financeiro_home'),
    path('new_request_financeiro', financeiro.new_request_financeiro, name='new_request_financeiro'),
    path('salvar_malote_financeiro', financeiro.salvar_malote_financeiro,
           name='salvar_malote_financeiro'),
    path('processos_financeiro', financeiro.processos_financeiro, name='processos_financeiro'),
    path('request_ci_fi', financeiro.request_ci_fi, name='request_ci_fi'),
    path('request_apontamentos_fi', financeiro.request_apontamentos_fi, name='request_apontamentos_fi'),

    path('cadastro_home', cadastro.cadastro_home, name='cadastro_home'),
    path('new_request_cadastro', cadastro.new_request_cadastro, name='new_request_cadastro'),
    path('salvar_malote_cadastro', cadastro.salvar_malote_cadastro, name='salvar_malote_cadastro'),
    path('processos_cadastro', cadastro.processos_cadastro, name='processos_cadastro'),
    path('request_ci_cad', cadastro.request_ci_cad, name='request_ci_cad'),
    path('request_apontamentos_cad', cadastro.request_apontamentos_cad, name='request_apontamentos_cad'),


    path('adm_home', adm.adm_home, name='adm_home'),
    path('new_request_adm', adm.new_request_adm, name='new_request_adm'),
    path('salvar_malote_adm', adm.salvar_malote_adm, name='salvar_malote_adm'),
    path('processos_adm', adm.processos_adm, name='processos_adm'),
    path('request_ci_adm', adm.request_ci_adm, name='request_ci_adm'),
    path('request_apontamentos_adm', adm.request_apontamentos_adm, name='request_apontamentos_adm'),


    path('cobranca_home', cobranca.cobranca_home, name='cobranca_home'),
    path('new_request_cobranca', cobranca.new_request_cobranca, name='new_request_cobranca'),
    path('salvar_malote_cobranca', cobranca.salvar_malote_cobranca, name='salvar_malote_cobranca'),
    path('processos_cobranca', cobranca.processos_cobranca, name='processos_cobranca'),
    path('request_ci_cob', cobranca.request_ci_cob, name='request_ci_cob'),
    path('request_apontamentos_cob', cobranca.request_apontamentos_cob, name='request_apontamentos_cob'),

    path('secretaria_home', secretaria.secretaria_home, name='secretaria_home'),
    path('new_request_secretaria', secretaria.new_request_secretaria, name='new_request_secretaria'),
    path('salvar_malote_secretaria', secretaria.salvar_malote_secretaria,name='salvar_malote_secretaria'),
    path('processos_secretaria', secretaria.processos_secretaria,name='processos_secretaria'),
    path('request_ci_sec', secretaria.request_ci_sec,name='request_ci_sec'),
    path('request_apontamentos_sec', secretaria.request_apontamentos_sec,name='request_apontamentos_sec'),

    path('credito_home', credito.credito_home, name='credito_home'),
    path('new_request_credito', credito.new_request_credito, name='new_request_credito'),
    path('salvar_malote_credito', credito.salvar_malote_credito, name='salvar_malote_credito'),
    path('processos_credito', credito.processos_credito, name='processos_credito'),
    path('request_ci_cre', credito.request_ci_cre, name='request_ci_cre'),
    path('request_apontamentos_cre', credito.request_apontamentos_cre, name='request_apontamentos_cre'),
    path('processos_credito', credito.processos_credito, name='processos_credito'),

    path('controladoria_home', controladoria.controladoria_home, name='controladoria_home'),
    path('new_request_PC', controladoria.new_request_PC, name='new_request_PC'),
    path('processos_PC', controladoria.processos_PC, name='processos_PC'),
    path('request_power_PC', controladoria.request_power_PC, name='request_power_PC'),
    path('request_propenso_PC', controladoria.request_propenso_PC, name='request_propenso_PC'),
    path('request_relatorio_PC', controladoria.request_relatorio_PC, name='request_relatorio_PC'),
    path('request_estudo_PC', controladoria.request_estudo_PC, name='request_estudo_PC'),
    path('request_apontamentos_pc', controladoria.request_apontamentos_pc, name='request_apontamentos_pc'),
    path('request_ci_pc', controladoria.request_ci_pc, name='request_ci_pc'),

    path('gestaoRisco_home', gestaoRisco.gestaoRisco_home, name='gestaoRisco_home'),
    path('request_acessos_risco', gestaoRisco.request_acessos_risco, name='request_acessos_risco'),
    path('new_request_risco', gestaoRisco.new_request_risco, name='new_request_risco'),
    path('processos_GR', gestaoRisco.processos_GR, name='processos_GR'),

    path('paDigital_home', padigital.paDigital_home, name='paDigital_home'),
    path('new_request_PaDigital', padigital.new_request_PaDigital, name='new_request_PaDigital'),
    path('request_acessos_PaDigital', padigital.request_acessos_PaDigital, name='request_acessos_PaDigital'),
    path('processos_PD', padigital.processos_PD, name='processos_PD'),

    path('padf_home', padf.padf_home, name='padf_home'),
    path('new_request_padf', padf.new_request_padf, name='new_request_padf'),
    path('salvar_malote_padf', padf.salvar_malote_padf, name='salvar_malote_padf'),
    path('processos_padf', padf.processos_padf, name='processos_padf'),

    path('planaltina_home', planaltina.planaltina_home, name='planaltina_home'),
    path('new_request_plan', planaltina.new_request_plan, name='new_request_plan'),
    path('processos_planaltina', planaltina.processos_planaltina, name='processos_planaltina'),
    path('salvar_malote_planaltina', planaltina.salvar_malote_planaltina, name='salvar_malote_planaltina'),

    path('formosa_home', formosa.formosa_home, name='formosa_home'),
    path('new_request_formosa', formosa.new_request_formosa, name='new_request_formosa'),
    path('salvar_malote_formosa', formosa.salvar_malote_formosa, name='salvar_malote_formosa'),
    path('processos_formosa', formosa.processos_formosa, name='processos_formosa'),

    path('vicente_home', vicente.vicente_home, name='vicente_home'),
    path('new_request_vicente', vicente.new_request_vicente, name='new_request_vicente'),
    path('salvar_malote_vicente', vicente.salvar_malote_vicente, name='salvar_malote_vicente'),
    path('processos_vicente', vicente.processos_vicente, name='processos_vicente'),

    path('SJ_home', saojoao.SJ_home, name='SJ_home'),
    path('new_request_SJ', saojoao.new_request_SJ, name='new_request_SJ'),
    path('salvar_malote_SJ', saojoao.salvar_malote_SJ, name='salvar_malote_SJ'),
    path('processos_SJ', saojoao.processos_SJ, name='processos_SJ'),

    path('saosebas_home', saosebas.saosebas_home, name='saosebas_home'),
    path('new_request_saosebas', saosebas.new_request_saosebas, name='new_request_saosebas'),
    path('salvar_malote_saosebas', saosebas.salvar_malote_saosebas, name='salvar_malote_saosebas'),
    path('processos_SB', saosebas.processos_SB, name='processos_SB'),

    path('marketing_home', marketing.marketing_home, name='marketing_home'),
    path('new_request_market', marketing.new_request_market, name='new_request_market'),
    path('processos_MK', marketing.processos_MK, name='processos_MK'),
    path('request_acessoria_MK', marketing.request_acessoria_MK, name='request_acessoria_MK'),
    path('request_digital_MK', marketing.request_digital_MK, name='request_digital_MK'),
    path('request_gráfica_MK', marketing.request_gráfica_MK, name='request_gráfica_MK'),
    path('request_ci_mk', marketing.request_ci_mk, name='request_ci_mk'),
    path('request_apontamentos_mk', marketing.request_apontamentos_mk, name='request_apontamentos_mk'),

    path('sia_home', sia.sia_home, name='sia_home'),
    path('new_request_sia', sia.new_request_sia, name='new_request_sia'),
    path('salvar_malote_sia', sia.salvar_malote_sia, name='salvar_malote_sia'),
    path('processos_sia', sia.processos_sia, name='processos_sia'),

    path('gestaoRecurso_home', gestaoRecursos.gestaoRecurso_home, name='gestaoRecurso_home'),
    path('recurso/new_request', gestaoRecursos.new_request_recurso, name='new_request_recurso'),
    path('request_ci_recurso', gestaoRecursos.request_ci_recurso, name='request_ci_recurso'),
    path('request_apontamentos_recurso', gestaoRecursos.request_apontamentos_recurso, name='request_apontamentos_recurso'),
    path('processos_recurso', gestaoRecursos.processos_recurso, name='processos_recurso'),
    path('request_portifolios', gestaoRecursos.request_portifolios, name='request_portifolios'),
    path('request_basileia', gestaoRecursos.request_basileia, name='request_basileia'),
    path('request_risco', gestaoRecursos.request_risco, name='request_risco'),
    path('request_contabilidade', gestaoRecursos.request_contabilidade, name='request_contabilidade'),

    path('recepcao_home', recepcao.recepcao_home, name='recepcao_home'),
    path('new_request_recepcao', recepcao.new_request_recepcao, name='new_request_recepcao'),
    path('salvar_malote_recepcao', recepcao.salvar_malote_recepcao, name='salvar_malote_recepcao'),
    path('request_ci_rec', recepcao.request_ci_rec, name='request_ci_rec'),
    path('request_apontamentos_rec', recepcao.request_apontamentos_rec, name='request_apontamentos_rec'),
    path('processos_recepcao', recepcao.processos_recepcao, name='processos_recepcao'),


    path('dev', pages.dev, name='dev'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
