# Generated by Django 4.2 on 2023-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosPessoais',
            fields=[
                ('idDadosPessoais', models.AutoField(db_column='idDadosPessoais', primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=60, null=True)),
                ('sexo', models.CharField(blank=True, max_length=45, null=True)),
                ('estadoCivil', models.CharField(blank=True, db_column='estadoCivil', max_length=45, null=True)),
                ('corRaca', models.CharField(blank=True, db_column='corRaca', max_length=45, null=True)),
                ('dataNascimento', models.DateField(blank=True, db_column='dataNascimento', null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoSanguineo', models.CharField(blank=True, db_column='tipoSanguineo', max_length=45, null=True)),
                ('nomePai', models.CharField(blank=True, db_column='nomePai', max_length=60, null=True)),
                ('nomeMae', models.CharField(blank=True, db_column='nomeMae', max_length=60, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('rg', models.CharField(blank=True, max_length=45, null=True)),
                ('expedidor', models.CharField(blank=True, max_length=45, null=True)),
                ('cnh', models.CharField(blank=True, max_length=45, null=True)),
                ('validadeCnh', models.DateField(blank=True, db_column='validadeCnh', null=True)),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
                ('tituloEleitor', models.CharField(blank=True, db_column='tituloEleitor', max_length=45, null=True)),
                ('zona', models.CharField(blank=True, max_length=45, null=True)),
                ('secao', models.CharField(blank=True, max_length=45, null=True)),
                ('ctps', models.CharField(blank=True, max_length=45, null=True)),
                ('serieCTPS', models.CharField(blank=True, db_column='serieCTPS', max_length=45, null=True)),
                ('dataCTPS', models.DateField(blank=True, db_column='dataCTPS', null=True)),
                ('reservista', models.CharField(blank=True, max_length=45, null=True)),
                ('ra', models.CharField(blank=True, db_column='RA', max_length=45, null=True)),
                ('serieReservista', models.CharField(blank=True, db_column='serieReservista', max_length=45, null=True)),
                ('pis', models.CharField(blank=True, max_length=45, null=True)),
                ('cns', models.CharField(blank=True, db_column='CNS', max_length=45, null=True)),
                ('pcd', models.CharField(blank=True, db_column='PCD', max_length=45, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('canvas', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
