# Generated by Django 4.2 on 2023-09-08 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='setor',
            fields=[
                ('idSetor', models.AutoField(db_column='idSetor', primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=45, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=45, null=True)),
                ('cor', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=45, null=True)),
                ('contato', models.CharField(blank=True, choices=[('', ''), ('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário')], max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, max_length=45, null=True)),
                ('unidade', models.CharField(blank=True, max_length=45, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=45, null=True)),
                ('atribuicoes', models.CharField(blank=True, max_length=45, null=True)),
                ('canvas', models.ImageField(blank=True, null=True, upload_to='setores')),
            ],
        ),
        migrations.CreateModel(
            name='solicitacoes',
            fields=[
                ('idSolicitacoes', models.AutoField(db_column='idrequestAcessosTI', primary_key=True, serialize=False)),
                ('assunto', models.CharField(max_length=45, null=True)),
                ('servico', models.CharField(max_length=45, null=True)),
                ('descricao', models.CharField(max_length=5000, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='processos')),
            ],
        ),
        migrations.CreateModel(
            name='profissional',
            fields=[
                ('idProfissional', models.AutoField(db_column='idProfissional', primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=45, null=True)),
                ('area', models.CharField(max_length=45, null=True)),
                ('paUnidade', models.CharField(blank=True, choices=[('', ''), ('00-SIA', '00-SIA'), ('01-PADF', '01-PADF'), ('02-FSA', '02-FSA'), ('03-SJA', '03-SJA'), ('06-PLA', '06-PLA'), ('07-VIP', '07-VIP'), ('08-AGC', '08-AGC'), ('09-SSB', '09-SSB'), ('97-DIG', '97-DIG'), ('98-OPE', '98-OPE'), ('99-UAD', '99-UAD')], db_column='paUnidade', max_length=45, null=True)),
                ('colaborador', models.CharField(blank=True, choices=[('', ''), ('Funcionário(a)', 'Funcionário(a)'), ('Tercerizado(a)', 'Tercerizado(a)'), ('Estagiário(a)', 'Estagiário(a)'), ('Menor Aprendiz', 'Menor Aprendiz'), ('Diretoria Executiva', 'Diretoria Executiva'), ('Diretoria Administrativa', 'Diretoria Administrativa'), ('Conselho Fiscal', 'Conselho Fiscal'), ('Conselho de Administração', 'Conselho de Administração')], max_length=60, null=True)),
                ('centroDeCusto', models.CharField(blank=True, db_column='centroDeCusto', max_length=45, null=True)),
                ('matricula', models.CharField(blank=True, max_length=45, null=True)),
                ('empregador', models.CharField(blank=True, choices=[('', ''), ('Sicoob Credibrasília', 'Sicoob Credibrasília'), ('Life Defense', 'Life Defense'), ('BS Soares', 'BS Soares')], max_length=45, null=True)),
                ('superiorImediato', models.CharField(blank=True, max_length=45, null=True)),
                ('folhaDePagamento', models.CharField(blank=True, max_length=45, null=True)),
                ('admissao', models.CharField(blank=True, max_length=45, null=True)),
                ('desligamento', models.CharField(blank=True, max_length=45, null=True)),
                ('situacao', models.CharField(choices=[('', ''), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=45, null=True)),
                ('horarioEntrada', models.TimeField(blank=True, db_column='horarioEntrada', max_length=45, null=True)),
                ('horarioSaida', models.TimeField(blank=True, db_column='horarioSaida', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outros',
            fields=[
                ('idOutros', models.AutoField(db_column='idOutros', primary_key=True, serialize=False)),
                ('camiseta', models.CharField(blank=True, choices=[('', ''), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='escolaridade',
            fields=[
                ('idEscolaridade', models.AutoField(db_column='idEscolaridade', primary_key=True, serialize=False)),
                ('entidadeDeEnsino', models.CharField(blank=True, db_column='entidadeDeEnsino', max_length=45, null=True)),
                ('curso', models.CharField(blank=True, db_column='curso', max_length=45, null=True)),
                ('grau', models.CharField(blank=True, choices=[('', ''), ('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], db_column='grau', max_length=45, null=True)),
                ('dataInicio', models.CharField(blank=True, max_length=45, null=True)),
                ('dataConclusao', models.CharField(blank=True, max_length=45, null=True)),
                ('idiomaSecundario', models.CharField(blank=True, db_column='idiomaSecundario', max_length=45, null=True)),
                ('nivelSecundario', models.CharField(blank=True, choices=[('', ''), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], db_column='nivelSecundario', max_length=45, null=True)),
                ('docEscolaridade', models.FileField(blank=True, null=True, upload_to='certificados')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolaridade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='enderecoContato',
            fields=[
                ('idEndereCoecontato', models.AutoField(db_column='idEnderecoEContato', primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, db_column='endereco', max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, db_column='bairro', max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=45, null=True)),
                ('estado', models.CharField(blank=True, choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], db_column='estado', max_length=45, null=True)),
                ('cep', models.CharField(blank=True, db_column='cep', max_length=45, null=True)),
                ('emailCorporativo', models.CharField(blank=True, db_column='emailCorporativo', max_length=45, null=True)),
                ('telefonePessoal', models.CharField(blank=True, db_column='telefonePessoal', max_length=45, null=True)),
                ('telefoneCorporativo', models.CharField(blank=True, db_column='telefoneCorporativo', max_length=45, null=True)),
                ('celularCorporativo', models.CharField(blank=True, db_column='celularCorporativo', max_length=45, null=True)),
                ('celularPessoal', models.CharField(blank=True, db_column='celularPessoal', max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, db_column='ramal', max_length=45, null=True)),
                ('emailPessoal', models.EmailField(blank=True, db_column='emailPessoal', max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=45, null=True)),
                ('telefoneDeEmergencia', models.CharField(blank=True, db_column='telefoneDeEmergencia', max_length=45, null=True)),
                ('celularDeEmergencia', models.CharField(blank=True, db_column='celularDeEmergencia', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecoContato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docTitulo',
            fields=[
                ('idTitulo', models.AutoField(db_column='idTitulo', primary_key=True, serialize=False)),
                ('documentoTitulo', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docTitulo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docRg',
            fields=[
                ('idRg', models.AutoField(db_column='idRg', primary_key=True, serialize=False)),
                ('documentoRg', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docRg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docResidencia',
            fields=[
                ('idResidencia', models.AutoField(db_column='idResidencia', primary_key=True, serialize=False)),
                ('documentoResidencia', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docResidencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docReservista',
            fields=[
                ('idReservista', models.AutoField(db_column='idReservista', primary_key=True, serialize=False)),
                ('documentoReservista', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docReservista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docPeriodico',
            fields=[
                ('idPeriodico', models.AutoField(db_column='idPeriodico', primary_key=True, serialize=False)),
                ('documentoPeriodico', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docPeriodico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docCursos',
            fields=[
                ('idCursos', models.AutoField(db_column='idCursos', primary_key=True, serialize=False)),
                ('curso', models.CharField(blank=True, max_length=45, null=True)),
                ('certiCurso', models.FileField(blank=True, null=True, upload_to='cursos')),
                ('data', models.DateField(blank=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCursos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docCpf',
            fields=[
                ('idCpf', models.AutoField(db_column='idCpf', primary_key=True, serialize=False)),
                ('documentoCpf', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCpf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docCnh',
            fields=[
                ('idCnh', models.AutoField(db_column='idCnh', primary_key=True, serialize=False)),
                ('documentoCnh', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCnh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docClt',
            fields=[
                ('idClt', models.AutoField(db_column='idClt', primary_key=True, serialize=False)),
                ('documentoClt', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docClt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docCertidao',
            fields=[
                ('idCertidao', models.AutoField(db_column='idCertidao', primary_key=True, serialize=False)),
                ('documentoCertidao', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCertidao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docAdmissional',
            fields=[
                ('idAdmissional', models.AutoField(db_column='idAdmissional', primary_key=True, serialize=False)),
                ('documentoAdmissional', models.FileField(blank=True, null=True, upload_to='documents')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docAdmissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dependentes',
            fields=[
                ('idDependentes', models.AutoField(db_column='idDependentes', primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('dataNascimento', models.CharField(blank=True, max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('contato', models.CharField(blank=True, max_length=45, null=True)),
                ('declaracao', models.CharField(blank=True, choices=[('', ''), ('Sim', 'Sim'), ('Não', 'Não')], max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dadosPessoais',
            fields=[
                ('idDadosPessoais', models.AutoField(db_column='idDadosPessoais', primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(db_column='nomeCompleto', max_length=60, null=True)),
                ('sexo', models.CharField(choices=[('', ''), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=45, null=True)),
                ('estadoCivil', models.CharField(blank=True, choices=[('', ''), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('União Estável', 'União Estável')], db_column='estadoCivil', max_length=45, null=True)),
                ('corRaca', models.CharField(blank=True, choices=[('', ''), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Indígena', 'Indígena'), ('Pardo', 'Pardo'), ('Preto', 'Preto')], db_column='corRaca', max_length=45, null=True)),
                ('dataNascimento', models.CharField(blank=True, max_length=45, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoSanguineo', models.CharField(blank=True, choices=[('', ''), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_column='tipoSanguineo', max_length=45, null=True)),
                ('nomePai', models.CharField(blank=True, db_column='nomePai', max_length=60, null=True)),
                ('nomeMae', models.CharField(blank=True, db_column='nomeMae', max_length=60, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('rg', models.CharField(blank=True, max_length=45, null=True)),
                ('expedidor', models.CharField(blank=True, max_length=45, null=True)),
                ('cnh', models.CharField(blank=True, max_length=45, null=True)),
                ('validadeCnh', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=45, null=True)),
                ('tituloEleitor', models.CharField(blank=True, db_column='tituloEleitor', max_length=45, null=True)),
                ('zona', models.CharField(blank=True, max_length=45, null=True)),
                ('secao', models.CharField(blank=True, max_length=45, null=True)),
                ('ctps', models.CharField(blank=True, max_length=45, null=True)),
                ('serieCTPS', models.CharField(blank=True, db_column='serieCTPS', max_length=45, null=True)),
                ('dataCTPS', models.CharField(blank=True, max_length=45, null=True)),
                ('reservista', models.CharField(blank=True, max_length=45, null=True)),
                ('ra', models.CharField(blank=True, db_column='RA', max_length=45, null=True)),
                ('serieReservista', models.CharField(blank=True, db_column='serieReservista', max_length=45, null=True)),
                ('pis', models.CharField(blank=True, max_length=45, null=True)),
                ('cns', models.CharField(blank=True, db_column='CNS', max_length=45, null=True)),
                ('pcd', models.CharField(blank=True, db_column='PCD', max_length=45, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users')),
                ('canvas', models.ImageField(blank=True, null=True, upload_to='canvas')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosPessoais', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dadosBancarios',
            fields=[
                ('idDadosBancarios', models.AutoField(db_column='idDadosBancarios', primary_key=True, serialize=False)),
                ('conta', models.CharField(blank=True, max_length=45, null=True)),
                ('digito', models.CharField(blank=True, db_column='digitoDaConta', max_length=45, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('agencia', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoDeConta', models.CharField(blank=True, choices=[('', ''), ('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário')], db_column='tipoDeConta', max_length=45, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('chavePix', models.CharField(blank=True, db_column='chavePix', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosBancarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='certificacao',
            fields=[
                ('idCertificacao', models.AutoField(db_column='idCertificacao', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=45, null=True)),
                ('organizacaoEmissora', models.CharField(blank=True, db_column='organizacaoEmissora', max_length=45, null=True)),
                ('dataEmissao', models.CharField(blank=True, max_length=45, null=True)),
                ('dataExpiracao', models.CharField(blank=True, max_length=45, null=True)),
                ('docCertificado', models.FileField(blank=True, null=True, upload_to='certificados')),
                ('certiAnbima', models.CharField(blank=True, choices=[('', ''), ('CPA-10', 'CPA-10'), ('CPA-20', 'CPA-20'), ('CEA', 'CEA'), ('Não possuo', 'Não possuo')], max_length=45, null=True)),
                ('anexoAnbima', models.FileField(blank=True, null=True, upload_to='certificados')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
