# Generated by Django 4.2 on 2023-05-04 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='corRaca',
            field=models.CharField(blank=True, choices=[('', ''), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Indígena', 'Indígena'), ('Pardo', 'Pardo'), ('Preto', 'Preto')], db_column='corRaca', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('', ''), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('União Estável', 'União Estável')], db_column='estadoCivil', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='nomeCompleto',
            field=models.CharField(db_column='nomeCompleto', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', ''), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='tipoSanguineo',
            field=models.CharField(blank=True, choices=[('', ''), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_column='tipoSanguineo', max_length=45, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='dadospessoais',
            order_with_respect_to='usuario',
        ),
        migrations.CreateModel(
            name='profissional',
            fields=[
                ('idProfissional', models.AutoField(db_column='idProfissional', primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.CharField(blank=True, max_length=45, null=True)),
                ('paUnidade', models.CharField(blank=True, choices=[('', ''), ('00-SIA', '00-SIA'), ('01-PADF', '01-PADF'), ('02-FSA', '02-FSA'), ('03-SJA', '03-SJA'), ('06-PLA', '06-PLA'), ('07-VIP', '07-VIP'), ('08-AGC', '08-AGC'), ('09-SSB', '09-SSB'), ('97-DIG', '97-DIG'), ('98-OPE', '98-OPE'), ('99-UAD', '99-UAD')], db_column='paUnidade', max_length=45, null=True)),
                ('colaborador', models.CharField(blank=True, choices=[('', ''), ('Funcionário(a)', 'Funcionário(a)'), ('Tercerizado(a)', 'Tercerizado(a)'), ('Estagiário(a)', 'Estagiário(a)'), ('Menor Aprendiz', 'Menor Aprendiz'), ('Diretoria Executiva', 'Diretoria Executiva'), ('Diretoria Administrativa', 'Diretoria Administrativa'), ('Conselho Fiscal', 'Conselho Fiscal'), ('Conselho de Administração', 'Conselho de Administração')], max_length=60, null=True)),
                ('centroDeCusto', models.CharField(blank=True, db_column='centroDeCusto', max_length=45, null=True)),
                ('matricula', models.CharField(blank=True, max_length=45, null=True)),
                ('empregador', models.CharField(blank=True, choices=[('', ''), ('Sicoob Credibrasília', 'Sicoob Credibrasília'), ('Life Defense', 'Life Defense'), ('BS Soares', 'BS Soares')], max_length=45, null=True)),
                ('superiorImediato', models.CharField(blank=True, max_length=45, null=True)),
                ('folhaDePagamento', models.CharField(blank=True, max_length=45, null=True)),
                ('admissao', models.CharField(blank=True, max_length=45, null=True)),
                ('desligamento', models.CharField(blank=True, max_length=45, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('', ''), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=45, null=True)),
                ('horarioEntrada', models.TimeField(blank=True, db_column='horarioEntrada', max_length=45, null=True)),
                ('horarioSaida', models.TimeField(blank=True, db_column='horarioSaida', max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='outros',
            fields=[
                ('idOutros', models.AutoField(db_column='idOutros', primary_key=True, serialize=False)),
                ('camiseta', models.CharField(blank=True, choices=[('', ''), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='escolaridade',
            fields=[
                ('idEscolaridade', models.AutoField(db_column='idEscolaridade', primary_key=True, serialize=False)),
                ('entidadeDeEnsino', models.CharField(blank=True, db_column='entidadeDeEnsino', max_length=45, null=True)),
                ('curso', models.CharField(blank=True, db_column='curso', max_length=45, null=True)),
                ('grau', models.CharField(blank=True, choices=[('', ''), ('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], db_column='grau', max_length=45, null=True)),
                ('dataInicio', models.DateField(blank=True, db_column='dataInicio', max_length=45, null=True)),
                ('dataConclusao', models.DateField(blank=True, db_column='dataConclusao', max_length=45, null=True)),
                ('idiomaPrimario', models.CharField(blank=True, db_column='idiomaPrimario', max_length=45, null=True)),
                ('nivelPrimario', models.CharField(blank=True, choices=[('', ''), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], db_column='nivelPrimario', max_length=45, null=True)),
                ('idiomaSecundario', models.CharField(blank=True, db_column='idiomaSecundario', max_length=45, null=True)),
                ('nivelSecundario', models.CharField(blank=True, choices=[('', ''), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], db_column='nivelSecundario', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='enderecoContato',
            fields=[
                ('idEndereCoecontato', models.AutoField(db_column='idEnderecoEContato', primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, db_column='endereco', max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, db_column='bairro', max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=45, null=True)),
                ('estado', models.CharField(blank=True, choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], db_column='estado', max_length=45, null=True)),
                ('cep', models.CharField(blank=True, db_column='cep', max_length=45, null=True)),
                ('emailCorporativo', models.CharField(blank=True, db_column='emailCorporativo', max_length=45, null=True)),
                ('telefonePessoal', models.CharField(blank=True, db_column='telefonePessoal', max_length=45, null=True)),
                ('telefoneCorporativo', models.CharField(blank=True, db_column='telefoneCorporativo', max_length=45, null=True)),
                ('celularCorporativo', models.CharField(blank=True, db_column='celularCorporativo', max_length=45, null=True)),
                ('celularPessoal', models.CharField(blank=True, db_column='celularPessoal', max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, db_column='ramal', max_length=45, null=True)),
                ('emailPessoal', models.EmailField(blank=True, db_column='emailPessoal', max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True)),
                ('nomeCompleto', models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True)),
                ('telefoneDeEmergencia', models.CharField(blank=True, db_column='telefoneDeEmergencia', max_length=45, null=True)),
                ('celularDeEmergencia', models.CharField(blank=True, db_column='celularDeEmergencia', max_length=45, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='dependentes',
            fields=[
                ('idDependentes', models.AutoField(db_column='idDependentes', primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('dataNascimento', models.DateField(blank=True, db_column='dataNascimento', max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('contato', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='dadosBancarios',
            fields=[
                ('idDadosBancarios', models.AutoField(db_column='idDadosBancarios', primary_key=True, serialize=False)),
                ('conta', models.CharField(blank=True, max_length=45, null=True)),
                ('digito', models.CharField(blank=True, db_column='digitoDaConta', max_length=45, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('agencia', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoDeConta', models.CharField(blank=True, choices=[('', ''), ('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário')], db_column='tipoDeConta', max_length=45, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('chavePix', models.CharField(blank=True, db_column='chavePix', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='certificacao',
            fields=[
                ('idCertificacao', models.AutoField(db_column='idCertificacao', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=45, null=True)),
                ('organizacaoEmissora', models.CharField(blank=True, db_column='organizacaoEmissora', max_length=45, null=True)),
                ('dataEmissao', models.DateField(blank=True, db_column='dataEmissao', max_length=45, null=True)),
                ('dataExpiracao', models.DateField(blank=True, db_column='dataExpiracao', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'usuario',
            },
        ),
    ]
