# Generated by Django 4.2 on 2023-04-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependentes',
            fields=[
                ('idDependentes', models.AutoField(db_column='idDependentes', primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(blank=True, db_column='nomeCompleto', max_length=45, null=True)),
                ('cpf', models.CharField(blank=True, max_length=45, null=True)),
                ('dataNascimento', models.CharField(blank=True, db_column='dataNascimento', max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('contato', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
