# Generated by Django 4.2 on 2024-03-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0002_kanbangroupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='authorFirst',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='authorLast',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasaida', models.CharField(max_length=100)),
                ('datafinal', models.CharField(max_length=100)),
                ('dataretorno', models.CharField(max_length=100)),
                ('diasausentes', models.CharField(max_length=100)),
                ('setorpa', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('colaborador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ferias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
