# Generated by Django 4.2 on 2023-11-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ccis', '0002_card_operatorrating_notification_messagehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=45, null=True)),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('cor', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, max_length=45, null=True)),
                ('contato', models.CharField(blank=True, max_length=45, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='group/')),
                ('url', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
