# Generated by Django 4.2 on 2023-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0002_remove_escolaridade_idiomaprimario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacao',
            name='dataEmissao',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='certificacao',
            name='dataExpiracao',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='canvas',
            field=models.ImageField(blank=True, null=True, upload_to='canvas'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='dataNascimento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='validadeCnh',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='dataNascimento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dataConclusao',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='dataInicio',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
