# Generated by Django 4.2 on 2023-12-01 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0002_card_operatorrating_messagehistory_cardsetorhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='card',
            name='operador',
        ),
        migrations.AddField(
            model_name='card',
            name='responsavel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='solicitante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
