# Generated by Django 4.2 on 2024-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0002_kanbangroupuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='authorFirst',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='authorLast',
            field=models.CharField(default='', max_length=255),
        ),
    ]
