# Generated by Django 4.2 on 2023-10-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0002_alter_cardsetorhistory_setor_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='colunaAtual',
        ),
    ]
