# Generated by Django 4.2 on 2023-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0002_sectorbuttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
