# Generated by Django 4.2 on 2023-04-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0002_dependentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='enderecoContato',
            fields=[
                ('idEndereCoecontato', models.AutoField(db_column='idEnderecoEContato', primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=45, null=True)),
                ('emailCorporativo', models.CharField(blank=True, db_column='emailCorporativo', max_length=45, null=True)),
                ('telefonePessoal', models.CharField(blank=True, db_column='telefonePessoal', max_length=45, null=True)),
                ('telefoneCorporativo', models.CharField(blank=True, db_column='telefoneCorporativo', max_length=45, null=True)),
                ('celularCorporativo', models.CharField(blank=True, db_column='celularCorporativo', max_length=45, null=True)),
                ('celularPessoal', models.CharField(blank=True, db_column='celularPessoal', max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, max_length=45, null=True)),
                ('emailPessoal', models.EmailField(blank=True, db_column='emailPessoal', max_length=45, null=True)),
                ('relacao', models.CharField(blank=True, max_length=45, null=True)),
                ('telefoneDeEmergencia', models.CharField(blank=True, db_column='telefoneDeEmergencia', max_length=45, null=True)),
                ('celularDeEmergencia', models.CharField(blank=True, db_column='celularDeEmergencia', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='escolaridade',
            fields=[
                ('idEscolaridade', models.AutoField(db_column='idEscolaridade', primary_key=True, serialize=False)),
                ('entidadeDeEnsino', models.CharField(blank=True, db_column='entidadeDeEnsino', max_length=45, null=True)),
                ('curso', models.CharField(blank=True, db_column='curso', max_length=45, null=True)),
                ('grau', models.CharField(blank=True, choices=[('', ''), ('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], db_column='grau', max_length=45, null=True)),
                ('dataConclusao', models.DateField(blank=True, db_column='dataConclusao', max_length=45, null=True)),
                ('idiomaPrimario', models.CharField(blank=True, db_column='idiomaPrimario', max_length=45, null=True)),
                ('idiomaSecundario', models.CharField(blank=True, db_column='idiomaSecundario', max_length=45, null=True)),
                ('nivelPrimario', models.CharField(blank=True, choices=[('', ''), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], db_column='nivelPrimario', max_length=45, null=True)),
                ('nivelSecundario', models.CharField(blank=True, choices=[('', ''), ('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], db_column='nivelSecundario', max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='dataNascimento',
            field=models.DateField(blank=True, db_column='dataNascimento', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='relacao',
            field=models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True),
        ),
    ]
