# Generated by Django 4.2 on 2023-05-08 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0002_dadospessoais_usuario_alter_dadospessoais_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosBancarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadosPessoais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dependentes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecoContato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolaridade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outros',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='rg',
            fields=[
                ('idRg', models.AutoField(db_column='idRg', primary_key=True, serialize=False)),
                ('documentoRg', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
