# Generated by Django 4.2 on 2023-05-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_alter_certificacao_dataemissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='dataCTPS',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
