# Generated by Django 4.2 on 2023-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_enderecocontato_escolaridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificacao',
            fields=[
                ('idCertificacao', models.AutoField(db_column='idCertificacao', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=45, null=True)),
                ('organizacaoEmissora', models.CharField(blank=True, db_column='organizacaoEmissora', max_length=45, null=True)),
                ('dataEmissao', models.DateField(blank=True, db_column='dataEmissao', max_length=45, null=True)),
                ('dataExpiracao', models.DateField(blank=True, db_column='dataExpiracao', max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='bairro',
            field=models.CharField(blank=True, db_column='bairro', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='cep',
            field=models.CharField(blank=True, db_column='cep', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='cidade',
            field=models.CharField(blank=True, db_column='cidade', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='endereco',
            field=models.CharField(blank=True, db_column='endereco', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='estado',
            field=models.CharField(blank=True, db_column='estado', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='ramal',
            field=models.CharField(blank=True, db_column='ramal', max_length=45, null=True),
        ),
    ]
