# Generated by Django 4.2 on 2023-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_remove_card_autor_remove_card_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroupinfo',
            name='url_home',
            field=models.TextField(blank=True, null=True),
        ),
    ]
