# Generated by Django 4.2 on 2023-11-03 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0003_card_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='compartilhar',
            field=models.ManyToManyField(blank=True, related_name='cards_compartilhados', to=settings.AUTH_USER_MODEL),
        ),
    ]
