# Generated by Django 4.2 on 2023-05-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0003_alter_certificacao_usuario_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='certificacao',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='dadosbancarios',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='dadospessoais',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='dependentes',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='enderecocontato',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='escolaridade',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='outros',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='profissional',
            order_with_respect_to=None,
        ),
        migrations.CreateModel(
            name='cnh',
            fields=[
                ('idCnh', models.AutoField(db_column='idCnh', primary_key=True, serialize=False)),
                ('documentoCnh', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
