# Generated by Django 4.2 on 2023-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_customgroupinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='setor_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='setor_atual',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='status_atual',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
