# Generated by Django 4.2 on 2024-03-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_notification_authorfirst_notification_authorlast_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferias',
        ),
    ]
