# Generated by Django 4.2 on 2023-12-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0003_card_compartilhar_card_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='setor_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='setor_atual',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='status_atual',
            field=models.CharField(max_length=100),
        ),
    ]
