# Generated by Django 4.2 on 2023-10-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ccis', '0004_cardsetorhistory_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('processador', models.CharField(max_length=100)),
                ('geracao', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('armazenamento', models.CharField(max_length=100)),
                ('gb', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('serviceTag', models.CharField(max_length=100)),
                ('antiVirus', models.CharField(max_length=100)),
                ('chaveWin', models.CharField(max_length=100)),
                ('chaveOffice', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='sector',
        ),
        migrations.AlterField(
            model_name='cardsetorhistory',
            name='setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
