# Generated by Django 4.2 on 2023-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0004_certificacao_alter_enderecocontato_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profissional',
            fields=[
                ('idprofissional', models.AutoField(db_column='idProfissional', primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.CharField(blank=True, max_length=45, null=True)),
                ('paUnidade', models.CharField(blank=True, choices=[('', ''), ('00-SIA', '00-SIA'), ('01-PADF', '01-PADF'), ('02-FSA', '02-FSA'), ('03-SJA', '03-SJA'), ('06-PLA', '06-PLA'), ('07-VIP', '07-VIP'), ('08-AGC', '08-AGC'), ('09-SSB', '09-SSB'), ('97-DIG', '97-DIG'), ('98-OPE', '98-OPE'), ('99-UAD', '99-UAD')], db_column='paUnidade', max_length=45, null=True)),
                ('colaborador', models.CharField(blank=True, choices=[('', ''), ('Funcionário(a)', 'Funcionário(a)'), ('Tercerizado(a)', 'Tercerizado(a)'), ('Estagiário(a)', 'Estagiário(a)'), ('Menor Aprendiz', 'Menor Aprendiz'), ('Diretoria Executiva', 'Diretoria Executiva'), ('Diretoria Administrativa', 'Diretoria Administrativa'), ('Conselho Fiscal', 'Conselho Fiscal'), ('Conselho de Administração', 'Conselho de Administração')], max_length=60, null=True)),
                ('centroDeCusto', models.CharField(blank=True, db_column='centroDeCusto', max_length=45, null=True)),
                ('matricula', models.CharField(blank=True, max_length=45, null=True)),
                ('empregador', models.CharField(blank=True, choices=[('', ''), ('Sicoob Credibrasília', 'Sicoob Credibrasília'), ('Life Defense', 'Life Defense'), ('BS Soares', 'BS Soares')], max_length=45, null=True)),
                ('superiorImediato', models.CharField(blank=True, max_length=45, null=True)),
                ('folhaDePagamento', models.CharField(blank=True, max_length=45, null=True)),
                ('admissao', models.CharField(blank=True, max_length=45, null=True)),
                ('desligamento', models.CharField(blank=True, max_length=45, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('', ''), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=45, null=True)),
                ('horarioEntrada', models.TimeField(blank=True, db_column='horarioEntrada', max_length=45, null=True)),
                ('horarioSaida', models.TimeField(blank=True, db_column='horarioSaida', max_length=45, null=True)),
                ('dataAtesAdmissional', models.DateField(blank=True, db_column='dataAtesAdmissional', max_length=45, null=True)),
                ('dataAtesPeriodico', models.DateField(blank=True, db_column='dataAtesPeriodico', max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='corRaca',
            field=models.CharField(blank=True, choices=[('', ''), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Indígena', 'Indígena'), ('Pardo', 'Pardo'), ('Preto', 'Preto')], db_column='corRaca', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('', ''), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('Separado(a)', 'Separado(a)'), ('União Estável', 'União Estável')], db_column='estadoCivil', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', ''), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='tipoSanguineo',
            field=models.CharField(blank=True, choices=[('', ''), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_column='tipoSanguineo', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='relacao',
            field=models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True),
        ),
    ]
