# Generated by Django 4.2 on 2023-05-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0004_alter_certificacao_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cnh',
            new_name='docCnh',
        ),
        migrations.RenameModel(
            old_name='rg',
            new_name='docRg',
        ),
        migrations.CreateModel(
            name='docCpf',
            fields=[
                ('idCpf', models.AutoField(db_column='idCpf', primary_key=True, serialize=False)),
                ('documentoCpf', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
