# Generated by Django 4.2 on 2024-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0004_alter_cardsetorhistory_setor_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroupinfo',
            name='periodo_arquivamento',
            field=models.IntegerField(default=10),
        ),
    ]
