# Generated by Django 4.2 on 2023-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0004_customgroupinfo_url_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroupinfo',
            name='url_home',
            field=models.URLField(blank=True, null=True),
        ),
    ]
