# Generated by Django 4.2 on 2024-03-19 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0005_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='colaborador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ferias', to=settings.AUTH_USER_MODEL),
        ),
    ]
