# Generated by Django 4.2 on 2023-05-09 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0005_rename_cnh_doccnh_rename_rg_docrg_doccpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccnh',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCnh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doccpf',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCpf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docrg',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docRg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='docTitulo',
            fields=[
                ('idTitulo', models.AutoField(db_column='idTitulo', primary_key=True, serialize=False)),
                ('documentoTitulo', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docTitulo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docResidencia',
            fields=[
                ('idResidencia', models.AutoField(db_column='idResidencia', primary_key=True, serialize=False)),
                ('documentoResidencia', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docResidencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docReservista',
            fields=[
                ('idReservista', models.AutoField(db_column='idReservista', primary_key=True, serialize=False)),
                ('documentoReservista', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docReservista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docPeriodico',
            fields=[
                ('idPeriodico', models.AutoField(db_column='idPeriodico', primary_key=True, serialize=False)),
                ('documentoPeriodico', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docPeriodico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docClt',
            fields=[
                ('idClt', models.AutoField(db_column='idClt', primary_key=True, serialize=False)),
                ('documentoClt', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docClt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docCertidao',
            fields=[
                ('idCertidao', models.AutoField(db_column='idCertidao', primary_key=True, serialize=False)),
                ('documentoCertidao', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCertidao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='docAdmissional',
            fields=[
                ('idAdmissional', models.AutoField(db_column='idAdmissional', primary_key=True, serialize=False)),
                ('documentoAdmissional', models.FileField(blank=True, null=True, upload_to='')),
                ('dataAtualizacao', models.DateField(auto_now=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docAdmissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
