# Generated by Django 4.2 on 2023-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0005_alter_dadospessoais_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacao',
            name='anexoAnbima',
            field=models.FileField(blank=True, null=True, upload_to='certificados'),
        ),
        migrations.AddField(
            model_name='certificacao',
            name='certiAnbima',
            field=models.CharField(blank=True, choices=[('', ''), ('CPA-10', 'CPA-10'), ('CPA-20', 'CPA-20'), ('CEA', 'CEA'), ('Não possuo', 'Não possuo')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='certificacao',
            name='docCertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados'),
        ),
        migrations.AddField(
            model_name='dependentes',
            name='declaracao',
            field=models.CharField(blank=True, choices=[('', ''), ('Sim', 'Sim'), ('Não', 'Não')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='docEscolaridade',
            field=models.FileField(blank=True, null=True, upload_to='certificados'),
        ),
        migrations.AlterField(
            model_name='docadmissional',
            name='documentoAdmissional',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='doccertidao',
            name='documentoCertidao',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='docclt',
            name='documentoClt',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='doccnh',
            name='documentoCnh',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='doccpf',
            name='documentoCpf',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='doccursos',
            name='certiCurso',
            field=models.FileField(blank=True, null=True, upload_to='cursos'),
        ),
        migrations.AlterField(
            model_name='docperiodico',
            name='documentoPeriodico',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='docreservista',
            name='documentoReservista',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='docresidencia',
            name='documentoResidencia',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='docrg',
            name='documentoRg',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='doctitulo',
            name='documentoTitulo',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='area',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cargo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='situacao',
            field=models.CharField(choices=[('', ''), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=45, null=True),
        ),
    ]
