# Generated by Django 4.2 on 2023-11-07 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0005_operatorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsetorhistory',
            name='operador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
