# Generated by Django 4.2 on 2023-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0005_profissional_alter_dadospessoais_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dadosBancarios',
            fields=[
                ('idDadosBancarios', models.AutoField(db_column='idDadosBancarios', primary_key=True, serialize=False)),
                ('conta', models.CharField(blank=True, max_length=45, null=True)),
                ('digito', models.CharField(blank=True, db_column='digitoDaConta', max_length=45, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('agencia', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoDeConta', models.CharField(blank=True, choices=[('', ''), ('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário')], db_column='tipoDeConta', max_length=45, null=True)),
                ('modalidade', models.CharField(blank=True, max_length=45, null=True)),
                ('chavePix', models.CharField(blank=True, db_column='chavePix', max_length=45, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='idprofissional',
            new_name='idProfissional',
        ),
    ]
