# Generated by Django 4.2 on 2023-10-13 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0005_notebook_remove_card_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='notebook',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notebook', to=settings.AUTH_USER_MODEL),
        ),
    ]
