# Generated by Django 4.2 on 2023-05-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0006_alter_doccnh_usuario_alter_doccpf_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='docCursos',
            fields=[
                ('idCursos', models.AutoField(db_column='idCursos', primary_key=True, serialize=False)),
                ('curso', models.CharField(blank=True, max_length=45, null=True)),
                ('certiCurso', models.FileField(blank=True, null=True, upload_to='')),
                ('data', models.DateField(blank=True, db_column='dataAtualizacao', max_length=45, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docCursos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
