# Generated by Django 4.2 on 2023-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0006_remove_notebook_responsavel_notebook_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
