# Generated by Django 4.2 on 2023-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0006_certificacao_anexoanbima_certificacao_certianbima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='setor',
            fields=[
                ('idSetor', models.AutoField(db_column='idSetor', primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=45, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=45, null=True)),
                ('cor', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=45, null=True)),
                ('contato', models.CharField(blank=True, choices=[('', ''), ('Conta Corrente', 'Conta Corrente'), ('Conta Poupança', 'Conta Poupança'), ('Conta Salário', 'Conta Salário')], max_length=45, null=True)),
                ('ramal', models.CharField(blank=True, max_length=45, null=True)),
                ('unidade', models.CharField(blank=True, max_length=45, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=45, null=True)),
                ('atribuicoes', models.CharField(blank=True, max_length=45, null=True)),
                ('canvas', models.ImageField(blank=True, null=True, upload_to='setores')),
            ],
        ),
    ]
