# Generated by Django 4.2 on 2023-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0006_dadosbancarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='outros',
            fields=[
                ('idOutros', models.AutoField(db_column='idOutros', primary_key=True, serialize=False)),
                ('camiseta', models.CharField(blank=True, choices=[('', ''), ('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=45, null=True)),
            ],
        ),
    ]
