# Generated by Django 4.2 on 2024-03-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0006_alter_ferias_colaborador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferias',
        ),
    ]
