# Generated by Django 4.2 on 2023-11-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroupinfo',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
