# Generated by Django 4.2 on 2023-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0008_customgroupinfo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
