# Generated by Django 4.2 on 2023-04-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0008_dadosbancarios_dadospessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosbancarios',
            old_name='dadosPessoa',
            new_name='dadosPessoais',
        ),
    ]
