# Generated by Django 4.2 on 2024-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0008_ferias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='authorFirst',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='authorLast',
        ),
    ]
