# Generated by Django 4.2 on 2024-03-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0009_remove_notification_authorfirst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='colaborador',
        ),
    ]
