# Generated by Django 4.2 on 2023-04-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0009_rename_dadospessoa_dadosbancarios_dadospessoais'),
    ]

    operations = [
        migrations.AddField(
            model_name='outros',
            name='dadosPessoais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccis.dadospessoais'),
        ),
    ]
