# Generated by Django 4.2 on 2024-03-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0010_remove_ferias_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='foto_solicitante',
            field=models.ImageField(blank=True, null=True, upload_to='solicitantes'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='nome_solicitante',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
