# Generated by Django 4.2 on 2024-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0011_ferias_foto_solicitante_ferias_nome_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='email_solicitante',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
