# Generated by Django 4.2 on 2024-03-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0012_ferias_email_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='email_solicitante',
        ),
        migrations.AddField(
            model_name='ferias',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
