# Generated by Django 4.2 on 2023-04-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0013_remove_outros_dadospessoais'),
    ]

    operations = [
        migrations.AddField(
            model_name='outros',
            name='dadosPessoais',
            field=models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
    ]
