# Generated by Django 4.2 on 2024-03-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0013_remove_ferias_email_solicitante_ferias_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='status',
            new_name='status_ferias',
        ),
    ]
