# Generated by Django 4.2 on 2024-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0014_rename_status_ferias_status_ferias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='status_ferias',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=100),
        ),
    ]
