# Generated by Django 4.2 on 2023-04-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0014_outros_dadospessoais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outros',
            name='dadosPessoais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
        ),
    ]
