# Generated by Django 4.2 on 2024-03-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0015_alter_ferias_status_ferias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ccis.card'),
        ),
        migrations.AddField(
            model_name='notification',
            name='authorFirst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='authorLast',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
