# Generated by Django 4.2 on 2023-04-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0015_alter_outros_dadospessoais'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacao',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='dadosPessoais',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependentes',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enderecocontato',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='dadosPessoais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
            preserve_default=False,
        ),
    ]
