# Generated by Django 4.2 on 2023-04-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0016_certificacao_dadospessoais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='dadosPessoais',
        ),
    ]
