# Generated by Django 4.2 on 2023-04-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0017_remove_dadospessoais_dadospessoais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='dadosPessoais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
        ),
        migrations.AlterField(
            model_name='outros',
            name='dadosPessoais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ccis.dadospessoais'),
        ),
    ]
