# Generated by Django 4.2 on 2024-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0017_alter_ferias_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
