# Generated by Django 4.2 on 2023-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0018_alter_dadosbancarios_dadospessoais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecocontato',
            name='nomeCompleto',
            field=models.CharField(blank=True, choices=[('', ''), ('Cônjuge', 'Cônjuge'), ('Filho(a)', 'Filho(a)'), ('Pais', 'Pais'), ('Outros', 'Outros')], max_length=45, null=True),
        ),
    ]
