# Generated by Django 4.2 on 2024-03-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0018_alter_ferias_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='nome_solicitante',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='foto_solicitante',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='solicitante',
        ),
        migrations.AddField(
            model_name='ferias',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuario'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
