# Generated by Django 4.2 on 2024-03-22 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0019_rename_nome_solicitante_ferias_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='nome',
            new_name='nome_solicitante',
        ),
        migrations.RemoveField(
            model_name='ferias',
            name='foto',
        ),
        migrations.AddField(
            model_name='ferias',
            name='foto_solicitante',
            field=models.ImageField(blank=True, null=True, upload_to='solicitantes'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
