# Generated by Django 4.2 on 2023-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0019_enderecocontato_nomecompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolaridade',
            name='dataInicio',
            field=models.DateField(blank=True, db_column='dataInicio', max_length=45, null=True),
        ),
    ]
