# Generated by Django 4.2 on 2023-05-05 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ccis', '0020_escolaridade_datainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosBancarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dadosPessoais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependentes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enderecocontato',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecoContato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolaridade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outros',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='nomeCompleto',
            field=models.CharField(db_column='nomeCompleto', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='enderecocontato',
            name='estado',
            field=models.CharField(blank=True, choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], db_column='estado', max_length=45, null=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='certificacao',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='dadosbancarios',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='dadospessoais',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='dependentes',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='enderecocontato',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='escolaridade',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='outros',
            order_with_respect_to='usuario',
        ),
        migrations.AlterOrderWithRespectTo(
            name='profissional',
            order_with_respect_to='usuario',
        ),
        migrations.RemoveField(
            model_name='certificacao',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='dadosbancarios',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='dependentes',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='enderecocontato',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='escolaridade',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='outros',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='dadosPessoais',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='dataAtesAdmissional',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='dataAtesPeriodico',
        ),
    ]
