# Generated by Django 4.2 on 2024-03-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0020_rename_nome_ferias_nome_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='usuario_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
