# Generated by Django 4.2 on 2024-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0021_ferias_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='usuario_id',
            new_name='nome_selecionado',
        ),
        migrations.AddField(
            model_name='ferias',
            name='id_selecionado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
