# Generated by Django 4.2 on 2024-03-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0022_rename_usuario_id_ferias_nome_selecionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferias',
            name='nome_solicitante',
        ),
    ]
