# Generated by Django 4.2 on 2024-03-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0023_remove_ferias_nome_solicitante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='foto_solicitante',
            new_name='foto_usuario_selecionado',
        ),
    ]
