# Generated by Django 4.2 on 2024-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccis', '0024_rename_foto_solicitante_ferias_foto_usuario_selecionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='nomecompleto_selecionado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
